title: Personality Quiz
email: your-email@example.com
description: >- 
  Choose a quiz category to find out which character you are most like!
baseurl: ""  # Usa una stringa vuota per il dominio principale
url: "https://moilolyta.github.io"  # Sostituisci 'username' con il tuo nome utente
twitter_username: your_twitter_username  # Modifica se necessario
github_username: your_github_username  # Modifica se necessario

# Impostazioni di build
theme: minima

# Opzionale: imposta il permalink
permalink: /:title/
